## Import Dependencies

In [2]:
import petpy
from petpy import Petfinder
#from config import API_key, API_secret
import json
import pymongo
import pandas as pd
from pprint import pprint

## API Call and Pandas DF Processing

In [5]:
API_key = "27jKhM4RCHNdKFJSd8U7JHMch9XX7h4nOMGxXkwZ8eYtC7NdIO"
API_secret = "BtQq6bC8DsaUX94WiYmvJgOLLXmePspqRmCaF4Pq"

In [6]:
pf = Petfinder(key=API_key, secret=API_secret)

In [7]:
# animals = pf.animals() - see below for query with edited results limits
animal_df = pf.animals(results_per_page=100, pages=100, return_df=True)

C:\Users\jvolo\anaconda4\envs\PythonData\lib\site-packages\petpy\api.py:1049: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  results_df = json_normalize(results[key])

In [8]:
animal2_df = animal_df.copy()

In [9]:
# get rid of extra organization_id column
my_columns = list(range(0,48))
animal2_df = animal2_df.iloc[:,my_columns]

In [10]:
# inspect list for column name formats
column_list = list(animal2_df.columns) 
column_list

['id',
 'organization_id',
 'url',
 'type',
 'species',
 'age',
 'gender',
 'size',
 'coat',
 'tags',
 'name',
 'description',
 'organization_animal_id',
 'photos',
 'primary_photo_cropped',
 'videos',
 'status',
 'status_changed_at',
 'published_at',
 'distance',
 'breeds.primary',
 'breeds.secondary',
 'breeds.mixed',
 'breeds.unknown',
 'colors.primary',
 'colors.secondary',
 'colors.tertiary',
 'attributes.spayed_neutered',
 'attributes.house_trained',
 'attributes.declawed',
 'attributes.special_needs',
 'attributes.shots_current',
 'environment.children',
 'environment.dogs',
 'environment.cats',
 'contact.email',
 'contact.phone',
 'contact.address.address1',
 'contact.address.address2',
 'contact.address.city',
 'contact.address.state',
 'contact.address.postcode',
 'contact.address.country',
 'animal_id',
 'animal_type',
 'organization_id',
 'primary_photo_cropped.small',
 'primary_photo_cropped.medium']

In [11]:
# change column header names in animal2_df to remove dot notation for mongo
animal3_df = animal2_df.rename(columns = {
 'breeds.primary':'breeds_primary',
 'breeds.secondary': 'breeds_secondary',
 'breeds.mixed': 'breeds_mixed',
 'breeds.unknown':'breeds_unknown',
 'colors.primary': 'colors_primary',
 'colors.secondary': 'colors_secondary',
 'colors.tertiary': 'colors_tertiary',
 'attributes.spayed_neutered': 'attributes_spayed_neutered',
 'attributes.house_trained': 'attributes_house_trained',
 'attributes.declawed': 'attributes_declawed',
 'attributes.special_needs': 'attributes_special_needs',
 'attributes.shots_current': 'attributes_shots_current',
 'environment.children': 'environment_children',
 'environment.dogs': 'environment_dogs',
 'environment.cats': 'environment_cats',
 'primary_photo_cropped.small': 'primary_photo_cropped_small',
 'primary_photo_cropped.medium': 'primary_photo_cropped_medium',
 'primary_photo_cropped.large': 'primary_photo_cropped_large',
 'primary_photo_cropped.full': 'primary_photo_cropped_full',
 'contact.email': 'contact_email',
 'contact.phone': 'contact_phone',
 'contact.address.address1': 'contact_address_address1',
 'contact.address.address2': 'contact_address_address2',
 'contact.address.city': 'contact_address_city',
 'contact.address.state': 'contact_address_state',
 'contact.address.postcode': 'contact_address_postcode',
 'contact.address.country': 'contact_address_country'})

In [12]:
animal3_df.head()

,id,organization_id,url,type,species,age,gender,size,coat,tags,...,contact_address_address2,contact_address_city,contact_address_state,contact_address_postcode,contact_address_country,animal_id,animal_type,organization_id,primary_photo_cropped_small,primary_photo_cropped_medium
0,50394527,TX2471,https://www.petfinder.com/dog/46533167-5039452...,Dog,Dog,Young,Female,Small,None,[],...,None,El Paso,TX,79906,US,50394527,dog,tx2471,NaN,NaN
1,50394526,OH528,https://www.petfinder.com/dog/zelda-yrly27-503...,Dog,Dog,Young,Female,Medium,None,[],...,None,Sidney,OH,45365,US,50394526,dog,oh528,NaN,NaN
2,50394524,NC121,https://www.petfinder.com/cat/sprout-50394524/...,Cat,Cat,Baby,Male,Small,Medium,[],...,None,Greensboro,NC,27404,US,50394524,cat,nc121,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...
3,50394517,IN522,https://www.petfinder.com/cat/woodstock-503945...,Cat,Cat,Young,Male,Medium,Short,[],...,None,Evansville,IN,47715,US,50394517,cat,in522,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...
4,50394523,NC121,https://www.petfinder.com/cat/julian-50394523/...,Cat,Cat,Adult,Male,Medium,Medium,[],...,None,Greensboro,NC,27404,US,50394523,cat,nc121,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...

In [13]:
organizations_df = pf.organizations(results_per_page=100, pages=100, return_df=True)

C:\Users\jvolo\anaconda4\envs\PythonData\lib\site-packages\petpy\api.py:1049: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  results_df = json_normalize(results[key])

In [14]:
# photos field is creating an error in pandas because it contains a list within the field. 
org_df = organizations_df.drop(columns=['photos'])

In [15]:
# change column header names to remove dot notation for mongo
org2_df = org_df.rename(columns = {
 'address.address1': "address_address1",
 'address.address2': "address_address2",
 'address.city': "address_city" ,
 'address.state': "address_state",
 'address.postcode': "address_postcode",
 'address.country': "address_country",
 'hours.monday': "hours_monday",
 'hours.tuesday': "hours_tuesday",
 'hours.wednesday': "hours_wednesday",
 'hours.thursday': "hours_thursday",
 'hours.friday': "hours_friday",
 'hours.saturday': "hours_saturday",
 'hours.sunday': "hours_sunday",
 'adoption.policy': "adoption_policy" ,
 'adoption.url': "adoption_url",
 'social_media.facebook': "socialmedia_facebook",
 'social_media.twitter': "socialmedia_twitter",
 'social_media.youtube': "socialmedia_youtube",
 'social_media.instagram': "socialmedia_instagram",
 'social_media.pinterest': "socialmedia_pinterest",
})

In [16]:
# now try to drop duplicates - based on all columns
org2_df.drop_duplicates()
# new length is 8932

,id,name,email,phone,url,website,mission_statement,distance,address_address1,address_address2,...,hours_saturday,hours_sunday,adoption_policy,adoption_url,socialmedia_facebook,socialmedia_twitter,socialmedia_youtube,socialmedia_instagram,socialmedia_pinterest,organization_id
0,PA912,The Shelter Animal Project,tsapadoption@gmail.com,None,https://www.petfinder.com/member/us/pa/fairles...,None,None,None,PO Box 24,None,...,None,None,None,None,None,None,None,None,None,pa912
1,GA762,Special Touch Animal Rescue,STARRadopt@aol.com,(404) 983-3581,https://www.petfinder.com/member/us/ga/acworth...,None,We are a private foster home group. We are NOT...,None,None,None,...,None,None,None,None,None,None,None,None,None,ga762
2,OH749,Purr-fect Companions Sanctuary,purrfectcompanions@att.net,216-671-6369,https://www.petfinder.com/member/us/oh/lakewoo...,None,None,None,P.O.Box 770992,None,...,None,None,None,None,None,None,None,None,None,oh749
3,TX876,Gina's Heart of Gold Reptile Rescue,gdisteldorf@comcast.net,(713) 329-9304,https://www.petfinder.com/member/us/tx/houston...,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,tx876
4,MO556,Montgomery City Animal Shelter/Project Preciou...,projectpreciouspaws@hotmail.com,1-573-310-4979,https://www.petfinder.com/member/us/mo/montgom...,None,None,None,915 Benton Street,None,...,None,None,None,None,None,None,None,None,None,mo556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,GA721,Kitty City Cat Rescue,kittycitymacon@yahoo.com,(478) 305-7799,https://www.petfinder.com/member/us/ga/macon/k...,http://www.kittycitycatrescue.com,Kitty City Cat Rescue is a Georgia State licen...,None,4530 Knight Road,None,...,None,None,"SPECIAL NOTICE:\r\n\r\nCurrently, Kitty City C...",https://static1.squarespace.com/static/59bec4f...,https://www.facebook.com/pg/KittyCityMacon/abo...,None,https://www.youtube.com/channel/UCujtEkys8g1jT...,None,http://www.pinterest.com/KittyCityGa,ga721
9996,NC675,Peak Lab Rescue,info@peaklabrescue.com,None,https://www.petfinder.com/member/us/nc/apex/pe...,http://www.peaklabrescue.com,"Last year, North Carolina euthanized more dogs...",None,PO Box 2184,None,...,None,None,Peak Lab Rescue does NOT have a facility to vi...,https://donorbox.org/20-non-refundable-applica...,http://www.facebook.com/peaklabrescue,None,None,http://www.instagram.com/peaklabrescue,None,nc675
9997,NJ234,Penny Angels Beagle Rescue,Beagler534@comcast.net,(609) 965-9476,https://www.petfinder.com/member/us/nj/ventnor...,http://www.pennyangelsbeaglerescue.com,Penny Angels Beagle Rescue is a non-profit org...,None,P.O. Box 2161,None,...,None,None,UPDATE FOR BEAGLE ADOPTIONS: Effective Saturd...,None,https://www.facebook.com/PennyAngelsBeagleRescue/,https://twitter.com/PennyAngelsBeag,None,None,None,nj234
9998,MD166,Best DAWG Rescue Inc.,dawg@dawg-rescue.org,None,https://www.petfinder.com/member/us/md/bethesd...,http://www.dawg-rescue.org.,After almost 20 years of providing rehabilitat...,None,None,None,...,None,None,None,http://www.dawg-rescue.org/application-form/,None,None,None,None,None,md166
9999,VA72,Animal Allies,Kim.Roman@animalalliesva.org,(703) 940-9183,https://www.petfinder.com/member/us/va/fairfax...,None,None,None,PO Box 7040,None,...,None,None,None,None,None,None,None,None,None,va72

## Lat and Long DF and Add to Org Collection

In [17]:
zipfile_df = pd.read_csv("col_resources/zip_lat_lon.csv")

In [18]:
zipcode_df = zipfile_df[["Zip", "Latitude", "Longitude"]]

In [19]:
#need to convert datatypes in order to merge dataframes 
convert_zipdict = {'Zip': str}
zip_converted_df = zipcode_df.astype(convert_zipdict)

In [20]:
#need to convert datatypes in order to merge dataframes
convert_orgdict = {'address_postcode': str}
org_converted_df = org2_df.astype(convert_orgdict)

In [21]:
#rename field in zipcode to merge with org df 
new_zip_df = zip_converted_df.rename(columns={'Zip': 'address_postcode'})

In [22]:
#merge zip code and org dataframes - now every org should have a corresponding latlong
org_zip_df = pd.merge(new_zip_df, org_converted_df,  how= "inner", on=["address_postcode", "address_postcode"])

In [23]:
org_zip2_df = org_zip_df.drop(columns=['organization_id'])

In [24]:
# rename id column (with CAPS) as organization_id column
org_zip3_df = org_zip2_df.rename(columns={'id': 'organization_id'})

In [25]:
# convert datatypes in order to merge dataframes 
convert_animaldict = {'id': float}
animal_conv_df = animal3_df.astype(convert_animaldict)

In [26]:
animal_conv_df.head()

,id,organization_id,url,type,species,age,gender,size,coat,tags,...,contact_address_address2,contact_address_city,contact_address_state,contact_address_postcode,contact_address_country,animal_id,animal_type,organization_id,primary_photo_cropped_small,primary_photo_cropped_medium
0,50394527.0,TX2471,https://www.petfinder.com/dog/46533167-5039452...,Dog,Dog,Young,Female,Small,None,[],...,None,El Paso,TX,79906,US,50394527,dog,tx2471,NaN,NaN
1,50394526.0,OH528,https://www.petfinder.com/dog/zelda-yrly27-503...,Dog,Dog,Young,Female,Medium,None,[],...,None,Sidney,OH,45365,US,50394526,dog,oh528,NaN,NaN
2,50394524.0,NC121,https://www.petfinder.com/cat/sprout-50394524/...,Cat,Cat,Baby,Male,Small,Medium,[],...,None,Greensboro,NC,27404,US,50394524,cat,nc121,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...
3,50394517.0,IN522,https://www.petfinder.com/cat/woodstock-503945...,Cat,Cat,Young,Male,Medium,Short,[],...,None,Evansville,IN,47715,US,50394517,cat,in522,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...
4,50394523.0,NC121,https://www.petfinder.com/cat/julian-50394523/...,Cat,Cat,Adult,Male,Medium,Medium,[],...,None,Greensboro,NC,27404,US,50394523,cat,nc121,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...,https://dl5zpyw5k3jeb.cloudfront.net/photos/pe...

## Merge DFs to One and Send to MongoDB

In [27]:
# all_df = pd.merge(animal_df, org2_df,  how= "inner", on=["organization_id", "organization_id"])
all_df = pd.merge(animal_conv_df, org_zip3_df, on=["organization_id", "organization_id"])

ValueError: The column label 'organization_id' is not unique.

In [28]:
conn = "mongodb://localhost:27017"
client = pymongo.MongoClient(conn)

In [29]:
db = client.rescue_angels_db

In [30]:
final_mongo_dict = all_df.to_dict("records")

NameError: name 'all_df' is not defined

In [31]:
db.final_data.insert_many(final_mongo_dict)

NameError: name 'final_mongo_dict' is not defined